### PR TITLE
add omi.js devtools links to readme

### PR DESCRIPTION
**Pull request by f**
Hi @dntzhang!

I created a simple yet useful Chrome DevTools extension for Omi, and added to the README! Please inspect: https://github.com/f/omi-devtools

It simply uses the Element panel's sidebar since Omi uses shadow dom and doesn't need another elements view such as React or Vue have. This makes it powerful while debugging.

### CODE REVIEW

**Comment by f** [comment]
Wow, that's also a fast merge!

**Comment by dntzhang** [comment]
You have done me a great favor.

**Comment by f** [comment]
Made that favor for everyone uses (will use) Omi! It's a competitive need for a "next-generation" framework nowadays.

**Comment by dntzhang** [comment]
How about adding dev-tools to the packages directory?

**Pull request merged**
